server:
  servlet:
    contextPath: /map-exercise
  port: 8080
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/task2
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop